import { Geist, Geist_Mono, Electrolize, Lexend } from "next/font/google";
import "./globals.css";
import Providers from "@/Component/Providers";
import { Toaster } from "@/components/ui/sonner";
import NavbarWrapper from "@/Component/NavbarWrapper";
import ProgressBarProvider from "@/Component/ProgressBarProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const electrolize = Electrolize({
  variable: "--font-electrolize",
  subsets: ["latin"],
  weight: ["400"],
});
const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${electrolize.variable} ${geistSans.variable} ${geistMono.variable} ${lexend.variable} font-sans antialiased`}
      >
        <Providers>
          {/* <ProgressBarProvider> */}
          <NavbarWrapper />
          {children}
          <Toaster />
          {/* </ProgressBarProvider> */}
        </Providers>
      </body>
    </html>
  );
}
